apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deploy
  labels:
    app: banking-mvn-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-mvn-app
  template:
    metadata:
      labels:
        app: banking-mvn-app
    spec:
      containers:
      - name: banking-mvn-container
        image: parmenderkumar/banking:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: banking-np-service
  labels:
    app: banking-mvn-app
spec:
  selector:
    app: banking-mvn-app

  type: NodePort
  ports:
  - nodePort: 31100
    port: 8081
    targetPort: 8081
